# Generated by Django 3.2.10 on 2022-03-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
