# Generated by Django 3.2.10 on 2022-03-12 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
