# Generated by Django 3.2.10 on 2022-04-07 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
    ]
