# Generated by Django 3.2.10 on 2022-04-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20220407_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='Fresh', max_length=150),
            preserve_default=False,
        ),
    ]
