# Generated by Django 3.2.10 on 2022-04-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20220419_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='morrisons_match',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sainsburys_match',
        ),
        migrations.RemoveField(
            model_name='product',
            name='waitrose_match',
        ),
    ]
