# Generated by Django 3.2.10 on 2022-04-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20220419_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='morrisons_match',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sainsburys_match',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='waitrose_match',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
